# Generated by Django 3.0.7 on 2020-07-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200711_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
    ]
