# Generated by Django 3.0.7 on 2020-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.IntegerField(default=1),
        ),
    ]
