# Generated by Django 3.0.7 on 2020-07-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200711_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hunters',
            new_name='customers',
        ),
    ]
